### ISSUE TITLE
kotnetcli crashes with BeautifulSoup error on Windows

### ISSUE THREAD

**Issue by GijsTimmers** [GijsTimmers/kotnetcli#93]
```
C:\Users\gijs\Desktop\kotnetcli>C:\Python27\python.exe kotnetcli-runner.py
Kotnet verbinding testen... [ OK ]
Netlogin openen............ [ OK ]
Gegevens invoeren.......... [ OK ]
Gegevens opsturen.......... [ OK ]
Traceback (most recent call last):
  File "kotnetcli-runner.py", line 23, in <module>
    main()
  File "C:\Users\gijs\Desktop\kotnetcli\kotnetcli\kotnetcli.py", line 346, in ma
in
    k.parseArgumenten()
  File "C:\Users\gijs\Desktop\kotnetcli\kotnetcli\kotnetcli.py", line 206, in pa
rseArgumenten
    worker.go(co, creds)
  File "C:\Users\gijs\Desktop\kotnetcli\kotnetcli\worker.py", line 75, in go
    self.login_resultaten(co)
  File "C:\Users\gijs\Desktop\kotnetcli\kotnetcli\worker.py", line 123, in login
_resultaten
    tup = self.browser.login_parse_results()
  File "C:\Users\gijs\Desktop\kotnetcli\kotnetcli\browser.py", line 133, in logi
n_parse_results
    soup = BeautifulSoup(self.html, "lxml")
  File "C:\Python27\lib\site-packages\bs4\__init__.py", line 156, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requeste
d: lxml. Do you need to install a parser library?

C:\Users\gijs\Desktop\kotnetcli>
```

**Comment by GijsTimmers** [comment]
Fixed. cc27a363fea5d271f450da8340065ee13bf8c637
